### ISSUE TITLE
Fail to build on Debian 12 due to unresolved import `std::panic::PanicHookInfo`

### ISSUE THREAD

**Issue by edheilr3c** [zee-editor/zee#102]
after running `cargo install --locked --features system-clipboard zee`  on Debian 12, results are:

```
error[E0432]: unresolved import `std::panic::PanicHookInfo`
 --> /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zee-0.4.0/src/panicking.rs:6:13
  |
6 |     panic::{PanicHookInfo, UnwindSafe},
  |             ^^^^^^^^^^^^^
  |             |
  |             no `PanicHookInfo` in `panic`
  |             help: a similar name exists in the module: `PanicInfo`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `zee` (bin "zee") due to 1 previous error
error: failed to compile `zee v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-install6Nwtwr`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Same error comes up if I don't include --features system-clipboard.

**Comment by edheilr3c** [comment]
As it happens, the same error comes up trying to compile on a Ubuntu 22.05 WSL environment.
